pipeline {
    agent any

    stages {
        stage('Terraform Init & Plan') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'aws-credentials',
                                                  usernameVariable: 'AWS_ACCESS_KEY_ID',
                                                  passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh '''
                      echo "Running Terraform..."

                      # move to your Terraform project folder
                      cd ProjectTerraform

                      # make sure workspace exists
                      terraform workspace select staging || terraform workspace new staging
                      terraform show
                      
                      # quick check that creds work
                      aws sts get-caller-identity || true

                      terraform init -input=false
                      terraform validate
                      terraform plan -out=tfplan
                    '''
                }
            }
        }
    }
}
